### ISSUE TITLE
Core/World: not loading the core - tries to load "camera" folder

### ISSUE THREAD

**Issue by LuigiElleBalotta** [LuigiElleBalotta/CypherCore#2]
While loading the core try to load the folder "camera"
According to TC, the folder "camera" is 3.3.5a only.

**Comment by hondacrx** [comment]
no the camera folder is for master for doing Cinematic cameras

**Comment by LuigiElleBalotta** [comment]
@hondacrx 
https://community.trinitycore.org/topic/12714-no-cameras-folder-after-extracting-maps-with-mapextractorexe/?#comment-78880

?

**Comment by hondacrx** [comment]
that is for 6.x  we are on 7.x which does have them. trust me use the map extractor and find out :)

**Comment by LuigiElleBalotta** [comment]
oh ok.. that's strange, i wonder why repacks doesn't provide them... I'm too lazy for extraction but.. i'll do it :D
